version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: eidoox
      POSTGRES_PASSWORD: eidoox99
      POSTGRES_DB: auctions_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  redis_data:
